name: Mac os Build & test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build:
          - name: "Build default options"
            cmake_options:

          - name: "Build shared library"
            cmake_options: -DUA_BUILD_SHARED_LIBS=ON

          - name: "Build amalgamation"
            cmake_options: -DUA_ENABLE_AMALGAMATION=ON

          - name: "Build with encryption"
            cmd_deps: brew install mbedtls
            cmake_options: -DUA_ENABLE_ENCRYPTION=MBEDTLS
          
          - name: "Build shared lib with encryption, amalgamation, and INLINEABLE_EXPORT"
            cmd_deps: brew install mbedtls
            cmake_options: -DUA_ENABLE_ENCRYPTION=MBEDTLS -DUA_ENABLE_AMALGAMATION=ON -DUA_ENABLE_INLINABLE_EXPORT=ON

    name: ${{ matrix.os }}-${{ matrix.build.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ matrix.build.runs_on == '' || matrix.build.runs_on == matrix.os }}
        with:
          submodules: true
      - name: Install Dependencies
        if: ${{ matrix.build.runs_on == '' || matrix.build.runs_on == matrix.os }}
        run: |
          ${{ matrix.build.cmd_deps }}
      - name: ${{ matrix.build.name }}
        if: ${{ matrix.build.runs_on == '' || matrix.build.runs_on == matrix.os }}
        run: |
          rm -rf build; mkdir -p build; cd build
          cmake .. ${{matrix.cmake_options}}
          cmake --build . -j sysctl -n hw.ncpu